// <auto-generated>
// Code generated by LUISGen SellerBot.json -cs Luis.TextRecognizer -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace EmptyBot
{
    public class TextRecognizer: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            AddCart, 
            GetQuote, 
            Greetings, 
            Help, 
            Login, 
            None, 
            RemoveCart, 
            RequestQuote, 
            Search, 
            Shop, 
            StartSearch
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Password;
            public string[] QuoteId;
            public string[] Username;
            public string[] VID;

            // Built-in entities
            public double[] number;

            // Regex entities
            public string[] PId;

            // Instance
            public class _Instance
            {
                public InstanceData[] Password;
                public InstanceData[] QuoteId;
                public InstanceData[] Username;
                public InstanceData[] VID;
                public InstanceData[] number;
                public InstanceData[] PId;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<TextRecognizer>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
